### ISSUE TITLE
Invalid "exports" main target "index.js" defined in the package config

### ISSUE THREAD

**Issue by stefanomozart** [then/is-promise#16] opened 2020-04-25 16:18 UTC
This error is displayed in node 13.13.0, when the package is-promise (v 2.2.0) is loaded

**Comment by kopax** [comment] 2020-04-25 16:20
I have the same error:

    Invalid "exports" main target "index.js" defined in the package config /mnt/mesos/sandbox/builds/rollup-umd/rollup-umd-ci-deploy/node_modules/is-promise/package.json\n' +

**Comment by szmarczak** [comment] 2020-04-25 16:23
It breaks AVA on Node.js 13.13.0.

/cc @novemberborn

**Comment by szmarczak** [comment] 2020-04-25 16:26
Also the release lacks `index.mjs`.

**Comment by RyanZim** [comment] 2020-04-25 16:27
Duplicate of https://github.com/then/is-promise/issues/12; fix is in https://github.com/then/is-promise/pull/15

**Comment by ljharb** [comment] 2020-04-25 17:32
See also, #19 - adding the "exports" field to a package is a breaking change, and shouldn't have happened in a minor version.

**Comment by MarkKragerup** [comment] 2020-04-25 17:50
If you are on NPM, run:
npm install is-promise@2.1.0 --save --save-exact

**Comment by ForbesLindesay** [comment] 2020-04-25 17:59
It should now be resolved. Since there are 4 issues about this, I'm going to close this issue in favour of #20. Please comment there if 2.2.1 does not fix your issue.

**Closed by ForbesLindesay** 2020-04-25 17:59 UTC
