### ISSUE TITLE
v2.2.0 issue with `npx create-react-app`

### ISSUE THREAD

**Issue by xfer** [then/is-promise#14] opened 2020-04-25 15:55 UTC
`npx create-react-app test`

```
npx: installed 99 in 6.053s
Must use import to load ES Module: /Users/<REDACTED>/.npm/_npx/93178/lib/node_modules/create-react-app/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /Users/<REDACTED>/.npm/_npx/93178/lib/node_modules/create-react-app/node_modules/is-promise/index.js from /Users/<REDACTED>/.npm/_npx/93178/lib/node_modules/create-react-app/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /Users/<REDACTED>/.npm/_npx/93178/lib/node_modules/create-react-app/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/<REDACTED>/.npm/_npx/93178/lib/node_modules/create-react-app/node_modules/is-promise/package.json.```

**Comment by RyanZim** [comment] 2020-04-25 15:57
Duplicate of https://github.com/then/is-promise/issues/12; package is currently broken. Pin to 2.1.0 until the issue is fixed.

**Comment by jovanailin** [comment] 2020-04-25 17:06
I am having the same issue with the same environment. I need the solution as quick as possible because I am overdue with a school project. Please someone help!

**Comment by Buildex** [comment] 2020-04-25 17:14
same for me :/

**Comment by sudir81** [comment] 2020-04-25 17:15
I have the same issue, i tried all possible ways
npx create-react-app
yarn create react-app
create-react-app

all are throwing same error

i have node (12.16.2), npm (6.14.4), yarn (1.21.1).

**Comment by Nir-002** [comment] 2020-04-25 17:15
got same issue...

**Comment by siyavash4812** [comment] 2020-04-25 17:16
Same issue but it happened when I added a new dependency to my react app 'video.js'

**Comment by aicayzer** [comment] 2020-04-25 17:18
same issue here

**Comment by Buildex** [comment] 2020-04-25 17:18
I've wrote a tweet, hope it goes to them... https://twitter.com/TheBuildex/status/1254097388081463296

**Comment by RyanZim** [comment] 2020-04-25 17:19
More detailed workaround for create-react-app https://github.com/facebook/create-react-app/issues/8896#issuecomment-619406384

**Comment by juank11memphis** [comment] 2020-04-25 17:19
Same problem here :(

**Comment by Buildex** [comment] 2020-04-25 17:22
Workaround worked for me :) hope this get fixed soon though: https://github.com/facebook/create-react-app/issues/8896#issuecomment-619406384

**Comment by ed-f-jones** [comment] 2020-04-25 17:52
Same here and my project is due in four days.

**Comment by mbreth** [comment] 2020-04-25 17:53
Same here. Nothing is working

**Comment by ForbesLindesay** [comment] 2020-04-25 17:59
It should now be resolved. Since there are 4 issues about this, I'm going to close this issue in favour of #20. Please comment there if 2.2.1 does not fix your issue.

**Closed by ForbesLindesay** 2020-04-25 17:59 UTC
