### ISSUE TITLE
ERR_INVALID_PACKAGE_TARGET

### ISSUE THREAD

**Issue by Sorunome** [then/is-promise#13] opened 2020-04-25 15:27 UTC
The module fails to import with node `v13.12.0`. The version 2.1.0 still works fine.

```
sorunome@sorunome-desktop repos/mx-puppet-skype $ node ./build/index.js                                 1
internal/modules/cjs/loader.js:616
            if (e.code !== 'ERR_PACKAGE_PATH_NOT_EXPORTED') throw e;
                                                            ^

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /home/sorunome/repos/mx-puppet-skype/node_modules/is-promise/package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:574:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:613:20)
    at applyExports (internal/modules/cjs/loader.js:503:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/sorunome/repos/mx-puppet-skype/node_modules/lowdb/lib/main.js:4:17) {
  code: 'ERR_INVALID_PACKAGE_TARGET'
}
```

**Comment by DeabitTech** [comment] 2020-04-25 15:41
so this is resolved?

**Comment by knrz** [comment] 2020-04-25 15:51
Nope, and it's broken serverless for me :(

**Comment by cipchk** [comment] 2020-04-25 15:51
Similar:

```
Unknown error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/vsts/work/1/s/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /home/vsts/work/1/s/node_modules/is-promise/index.js from /home/vsts/work/1/s/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/vsts/work/1/s/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/vsts/work/1/s/node_modules/is-promise/package.json.
```

A full log refer to [azure pipelines](https://dev.azure.com/ng-alain/delon/_build/results?buildId=285&view=logs&jobId=8cd93bc0-71e1-511b-b3fe-5b5711bf4f27&j=8cd93bc0-71e1-511b-b3fe-5b5711bf4f27&t=30c981be-7518-5654-ec2d-5d59fb481b12)

**Comment by Sorunome** [comment] 2020-04-25 15:54
> so this is resolved?

Nope, it got broken in the `2.2.0` update about an hour ago and there is no fix for it yet

**Comment by monken** [comment] 2020-04-25 15:54
The left pad fiasco all over. https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

It's a single line of code. Why do we need a package for this?

**Comment by onhate** [comment] 2020-04-25 15:54
Same is happening to me, started some minutes ago:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../node_modules/is-promise/index.js
require() of ES modules is not supported.
```

**Comment by samblake** [comment] 2020-04-25 15:55
Broke Serverless for me too! :(

**Comment by RyanZim** [comment] 2020-04-25 15:57
Duplicate of https://github.com/then/is-promise/issues/12.

**Comment by knrz** [comment] 2020-04-25 16:03
If you're using Yarn [here's a fix](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/):

1. Run `yarn why is-promise`
2. For every package that depends on `is-promise`, pin the resolution. In my case, `serverless` was installing `run-async` and `memoizee`, which each had their own copy of `is-promise`. I added the following key to my `package.json`:

```json
  "resolutions": {
    "is-promise": "2.1.0",
    "run-async/is-promise": "2.1.0",
    "memoizee/is-promise": "2.1.0"
  }
```

Then I `rm -rf`'d the directories with `run-async` and `memoizee` and reinstalled them using `yarn add`. Works for me 👍

**Comment by mistakenot** [comment] 2020-04-25 16:10
Broke create-react-app for me. 
```
$ npx create-react-app my-app
npx: installed 99 in 7.558s
Must use import to load ES Module: /home/charlie/.npm/_npx/20884/lib/node_modules/create-react-app/node_modules/is-promise/index.js
require() of ES modules is not supported.
```

**Comment by crsohr** [comment] 2020-04-25 16:59
If you're using npm, you can fix the issue by editing your `package-lock.json` file like so.

Identify the modules that are using the failing `is-promise` modules:

```javascript
 "run-async": {                                                                                                                                                                                                                
      "version": "2.4.0",                                                                                                                                                                                                         
      "resolved": "https://registry.npmjs.org/run-async/-/run-async-2.4.0.tgz",                                                                                                                                                   
      "integrity": "sha512-xJTbh/d7Lm7SBhc1tNvTpeCHaEzoyxPrqNlvSdMfBTYwaY++UJFyXUOxAtsRUXjlqOfj8luNaR9vjCh4KeV+pg==",                                                                                                             
      "dev": true,                                                                                                                                                                                                                
      "requires": {                                                                                                                                                                                                               
        "is-promise": "^2.1.0"                                                                                                                                                                                                    
      }                                                                                                                                                                                                                           
    },
```

Move the `is-promise` out of `requires` and create a new object `dependencies`:

```javascript
"run-async": {                                                                                                                                                                                                                
      "version": "2.4.0",                                                                                                                                                                                                         
      "resolved": "https://registry.npmjs.org/run-async/-/run-async-2.4.0.tgz",                                                                                                                                                   
      "integrity": "sha512-xJTbh/d7Lm7SBhc1tNvTpeCHaEzoyxPrqNlvSdMfBTYwaY++UJFyXUOxAtsRUXjlqOfj8luNaR9vjCh4KeV+pg==",                                                                                                             
      "dev": true,                                                                                                                                                                                                                
      "dependencies": {                                                                                                                                                                                                           
        "is-promise": {                                                                                                                                                                                                           
          "version": "2.1.0"                                                                                                                                                                                                      
        }                                                                                                                                                                                                                         
      }                                                                                                                                                                                                                           
},
```

Next, rerun `npm install --only=dev` and you should be good.

(If using yarn, see comment #13)

**Comment by akctba** [comment] 2020-04-25 17:11
> package-lock.jso

but how to do it to create a new project?

**Comment by alexandernst** [comment] 2020-04-25 17:19
😂  holy shit 😂  JS ecosystem is just utterly broken beyond any repair.

**Comment by SimonSchick** [comment] 2020-04-25 17:20
Fyi, this is on hackernews, except a lot attention/comments.

**Comment by jcao219** [comment] 2020-04-25 17:21
https://deno.land/ piling on the bandwagon

**Comment by aeolingamenfel** [comment] 2020-04-25 17:27
This also seems to be affecting latest on [firebase-tools](https://www.npmjs.com/package/firebase-tools).

**Comment by crsohr** [comment] 2020-04-25 17:39
> This also seems to be affecting latest on [firebase-tools](https://www.npmjs.com/package/firebase-tools).

This is affecting so many packages, this is also affecting [npx eslint --init](https://eslint.org/docs/user-guide/getting-started) 😥

**Comment by DesWurstes** [comment] 2020-04-25 17:40
[Now on HN](https://news.ycombinator.com/item?id=22979245)

**Comment by MarkKragerup** [comment] 2020-04-25 17:47
If you are on NPM, run:
npm install is-promise@2.1.0 --save --save-exact

**Comment by preetjdp** [comment] 2020-04-25 17:52
> If you are on NPM, run:
> npm install is-promise@2.1.0 --save --save-exact

Does this work if a 3rd party dependency uses `is-promise` ?

**Comment by jschuur** [comment] 2020-04-25 17:54
> Does this work if a 3rd party dependency uses `is-promise` ?

It just did for me.

**Comment by MarkKragerup** [comment] 2020-04-25 17:54
> > If you are on NPM, run:
> > npm install is-promise@2.1.0 --save --save-exact
> 
> Does this work if a 3rd party dependency uses `is-promise` ?

I'm unsure exactly what dependencies i have that were broken - but it was for sure more than one. It's some big projects, worked on all of them.

**Comment by FdezRomero** [comment] 2020-04-25 17:58
Version 2.2.1 released: https://github.com/then/is-promise/releases/tag/2.2.1

**Comment by tyvdh** [comment] 2020-04-25 17:59
> If you are on NPM, run:
> npm install is-promise@2.1.0 --save --save-exact

Didn't work for me :(

**Comment by ForbesLindesay** [comment] 2020-04-25 18:00
It should now be resolved. Since there are 4 issues about this, I'm going to close this issue in favour of #20. Please comment there if 2.2.1 does not fix your issue.

**Closed by ForbesLindesay** 2020-04-25 18:00 UTC
